name: values log test

on:
  workflow_dispatch:
  push:
    branches: master
    paths-ignore:
      - '*'
      - '!.github/workflows/build-ndk.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: true
          lfs: true
      - name: log context
        run: |
          echo "$GITHUB_CONTEXT"
          echo ${{ github }}
          echo ${{ github.actor }}
